# Generated by Django 4.2.6 on 2024-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
